# **加载与保存当量**

In [4]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x, 'x-file') # 保存

In [5]:
x2 = torch.load('x-file') # 读取
x2

tensor([0, 1, 2, 3])

In [6]:
# 张量列表
y = torch.zeros(4)
torch.save([x, y], 'x-file')
x2, y2 = torch.load('x-file')
x2, y2

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [7]:
# 字典
mydict = {'x':x, 'y':y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

# **加载和保存模型参数**

In [9]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.out = nn.Linear(256, 10)
    def forward(self, X):
        return self.out(F.relu(self.hidden(X)))

net = MLP()
X = torch.randn(size=(2, 20))
Y=net(X)


In [10]:
# 保存模型参数
torch.save(net.state_dict(), 'mlp-params')

In [11]:
# 读取保存的模型参数
clone = MLP()
clone.load_state_dict(torch.load('mlp-params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (out): Linear(in_features=256, out_features=10, bias=True)
)

In [13]:
Y_clone = clone(X)
Y == Y_clone

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])